version: '3.8'

volumes:
  postgres_data:

services:
  db:
    image: postgres:13
    restart: always
    container_name: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  redis:
    image: redis:6.0.10
    container_name: redis
    env_file:
      - ./.env

  celery:
    build: .
    command: celery -A mysite worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    command: celery -A mysite beat -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

  sibdev_api:
    build: .
    container_name: sibdev_api
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    container_name: webserver
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    ports:
      - "80:80"
    depends_on:
      - sibdev_api