# Generated by Django 3.2.7 on 2021-09-27 18:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrioritiesNameModel',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Full name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrioritiesModel',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('importance', models.IntegerField(validators=[django.core.validators.MinValueValidator(-11), django.core.validators.MaxValueValidator(11)], verbose_name='Importance')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='precedents', to='accounts.account', verbose_name='Account')),
                ('priorities_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='precedents', to='priorities.prioritiesnamemodel', verbose_name='Priorities name')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
