# Generated by Django 3.2.7 on 2021-09-28 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('priorities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prioritiesmodel',
            options={'verbose_name': 'Prioritie', 'verbose_name_plural': 'Priorities'},
        ),
        migrations.AlterModelOptions(
            name='prioritiesnamemodel',
            options={'verbose_name': 'Prioritie name', 'verbose_name_plural': 'Prioritie names'},
        ),
        migrations.AlterUniqueTogether(
            name='prioritiesmodel',
            unique_together={('account', 'priorities_name')},
        ),
    ]
