# Generated by Django 3.2.7 on 2021-09-27 18:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Confirmed')),
                ('name', models.CharField(max_length=255, verbose_name='Full name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('confirmation_code', models.UUIDField(default=uuid.uuid4, verbose_name='Confirmation code')),
                ('account', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='email_confirmation', to='accounts.account', verbose_name='Account')),
            ],
            options={
                'verbose_name': 'Email confirmation',
                'verbose_name_plural': 'Email confirmations',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='EmailConfirmationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('sent_code', models.UUIDField(verbose_name='Sent code')),
                ('success', models.BooleanField(verbose_name='Success')),
                ('error', models.TextField(blank=True, verbose_name='Error')),
                ('email_confirmation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmation_messages', to='accounts.emailconfirmation', verbose_name='Email confirmation')),
            ],
            options={
                'verbose_name': 'Email confirmation message',
                'verbose_name_plural': 'Email confirmation messages',
                'ordering': ('-id',),
            },
        ),
    ]
